version: '3'
services:
  factorio:
    image: factoriotools/factorio:stable
    restart: unless-stopped
    ports:
      - 34197:34197/udp
      - 27015:27015/tcp
    volumes:
      - ./factorio:/factorio
